### ISSUE TITLE
Add support for a wider range of image formats 

### ISSUE THREAD

**Issue by FredHappyface** [rzhou1999/woosticker#10]
Hi thank you so much for this project! It's coming on really nicely and certainly fixes the issues caused by the recent gboard update.

Would it be possible to add support for some other image formats? (It's be really nice to see jpg and webp for my use case) 

I seem to remember reading that webp was pretty well supported by new ish versions of Android so I imagine it'll just be a case of updating the image mapping you are are using? 

Thanks again for all your time on this 😊

**Comment by FredHappyface** [comment]
According to https://developer.android.com/guide/topics/graphics/drawables gif, png and jpg are supported out of the box but I've found the following that may help?

https://github.com/zjupure/GlideWebpDecoder/blob/master/webp_decoder/src/main/java/com/bumptech/glide/integration/webp/decoder/WebpDrawable.java

**Comment by rzhou1999** [comment]
Appreciate the links-- I've been meaning to get around to this actually. jpg support should be as easy as changing [this function](https://github.com/rzhou1999/woosticker/blob/main/app/src/main/java/com/woosticker/Utils.java#L29), actually. For other formats such as webp, you've actually identified the main annoyance-- Drawable support is limited and doesn't even support animated gifs. I'll take a look at WebpDrawable.java, although that might have to wait a bit.
