### ISSUE TITLE
Feature: Sticker Sort Order 

### ISSUE THREAD

**Issue by FredHappyface** [rzhou1999/woosticker#15]
usticker allows you to sort stickers so it would be useful if this could be a toggle in woosticker. Happy to make a pr for this 

Thanks 😊

**Comment by rzhou1999** [comment]
I was thinking about this too and was hoping to get to it soon. How did usticker do it? Alphabetical? I was thinking an optional UI for manual sorting might also be useful for smaller sets, a la https://inspirecoding.app/lessons/swipedelete-and-reorder-items/

**Comment by FredHappyface** [comment]
I'd probably just add a-z ascending and descending tbh and expect the user to name stickers accordingly if they want a specific sort order
