### ISSUE TITLE
Choose A License 

### ISSUE THREAD

**Issue by FredHappyface** [rzhou1999/woosticker#18]
I've just noticed that this project doesn't have a license.

Please take a look at https://choosealicense.com/ and add some license ASAP (I'm personally pretty fond of the MIT license but there's loads to choose from)

Thank you for your time

**Comment by rzhou1999** [comment]
See latest commit. Unfortunately I've been swamped with research projects and paper assignments as of late so haven't had much time to address the longer PRs/issues. I'll try to get around to responding to your other PRs as soon as I can but this is all I have time for right now. As always, thank you for the help.
