### ISSUE TITLE
Add one back button

### ISSUE THREAD

**Issue by suraj3486** [rzhou1999/woosticker#3]
Please add one <- back button at beginning in top bar where folder icons are shown which will take back to normal keyboard

**Comment by rzhou1999** [comment]
Don't think this is technically possible, and definitely not without system priveleges. See https://stackoverflow.com/questions/11036435/switch-keyboard-profile-programmatically#12891236 for some background-- I could add a button that asks the user to switch keyboards, but that's equivalent to pressing the button in the bottom right.

Unfortunately since woosticker is a system keyboard, it has to play by android rules (i.e. the idea that an app is not allowed to stealth-change the input method because the user should have complete control over a system aspect like that) so I'm a little limited in what I can and can't do.

**Comment by suraj3486** [comment]
Than add a switch which ask for keyboard switch and thanx for the app.
I was really searching for an app after uSticker

**Comment by Hilmic** [comment]
Thank you so much for creating an alternative to uSticker! 👍 
I'd also like to have an easier method to switch back to the original keyboard, therefore I second the feature request for a toggle button.

**Comment by rzhou1999** [comment]
> Than add a switch which ask for keyboard switch and thanx for the app.
> I was really searching for an app after uSticker

Doesn't that already exist via the system itself? Don't see the point in cluttering the UI for a redundant feature

**Comment by suraj3486** [comment]
It is only available in 3 button navigation. But if u use A11 gesture than there is no button to switch keyboard

**Comment by suraj3486** [comment]
It is only available in 3 button navigation. But if u use A11 gesture than there is no button to switch keyboard

**Comment by suraj3486** [comment]
It is only available in 3 button navigation. But if u use A11 gesture than there is no button to switch keyboard

**Comment by suraj3486** [comment]
It is only available in 3 button navigation. But if u use A11 gesture than there is no button to switch keyboard

**Comment by rzhou1999** [comment]
Please don't spam-- rest assured I'll see the issue.

I don't quite understand what you mean by it only existing on three button ui-- this is what I see:

![Screenshot_20210411-125813.png](https://user-images.githubusercontent.com/18129258/114313773-dd7b1d00-9ac5-11eb-9c92-143161532dc0.png)

**Comment by Hilmic** [comment]
Here's what I see (Android 10, MIUI Global 12.0.4, nothing modified):

![Screenshot_2021-04-11-19-29-05-421_ch threema app](https://user-images.githubusercontent.com/26696883/114314817-93615e00-9afc-11eb-95bd-53d637bab1d2.jpg)

**Comment by rzhou1999** [comment]
@Hilmic ah, google strikes again. Didn't realize that this wasn't an option on all android versions (I've only used 11). I can try to add an option to allow for this back button.

**Comment by Hilmic** [comment]
That would be great and simplify switching back to the standard keyboard :)

**Comment by rzhou1999** [comment]
Alright, so I just grabbed an icon from [tabler](https://github.com/tabler/tabler-icons) and just threw together a back button. How's this?

![image](https://user-images.githubusercontent.com/18129258/114319137-26d76680-9ade-11eb-840c-7138114c76fd.png)

Won't update versions just yet (want to see if I can get in configurable window height and the like first), but feel free to build manually in the meantime.

**Comment by rzhou1999** [comment]
Released.

**Comment by Hilmic** [comment]
Looks great!
