### ISSUE TITLE
Keyboard switch

### ISSUE THREAD

**Issue by suraj3486** [rzhou1999/woosticker#9]
As u have posted images of app. It is only available in 3 button navigation. But if u use A11 gesture than there is no button to switch keyboard.
That is why a inbuilt keyboard switcher button is needed

**Comment by Hilmic** [comment]
I've 3 button navigation activated but my ROM doesn't show a keyboard switch button...

**Comment by rzhou1999** [comment]
> I've 3 button navigation activated but my ROM doesn't show a keyboard switch button...

Hm interesting. I've reopened the original issue then-- can you take a look at the image I added there and post what you see? Environment would also be helpful (which android version, any custom things, etc.).

#3
